# Generated by Django 2.2.7 on 2019-11-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191115_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
    ]
