# Generated by Django 2.2.7 on 2019-11-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_collection_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='picture',
        ),
        migrations.AddField(
            model_name='collection',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='collection', to='blog.Picture'),
        ),
    ]
